name: Build and push artifacts
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run the analyser tests
        run: |
          yarn install
          yarn test
  Build-And-Push:
    runs-on: ubuntu-latest
    needs: Tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install prerequesites to build & push
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.23.0/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin
          wget https://github.com/mikefarah/yq/releases/download/v4.7.1/yq_linux_amd64 -O yq && chmod +x yq && sudo mv yq /usr/local/bin/yq
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build the tagged images
        env:
          DOCKER_BUILDKIT: 1
        run: PUSH=true skaffold build
      - name: Build the latest images
        env:
          DOCKER_BUILDKIT: 1
        run: LATEST=true PUSH=true skaffold build
      - name: Check out the GitOPS repo
        uses: actions/checkout@v2
        with:
          repository: watnwy/gitops
          ref: master
          token: ${{ secrets.EXPANDED_GITHUB_TOKEN }}
      - name: Bump the used image
        run: |
          export TAG=prod-`echo $GITHUB_SHA | cut -c1-7`
          yq e ".watnwy.analysers.node.image = \"233632450084.dkr.ecr.eu-west-1.amazonaws.com/watnwy-node-analyser:${TAG}\"" -i watnwy/values-prod.yaml
          git config --global user.email "github-actions@watnwy.com"
          git config --global user.name "GithubActions"
          git add watnwy/values-prod.yaml
          git diff --staged
          git commit -m "[GithubAction] Bump the Node analyser image to tag ${TAG}"
          git push origin master
